### ISSUE TITLE
New Feature - Option to allow login and destroy other sessions

### ISSUE THREAD

**Issue by Joel-James** [Joel-James/loggedin#2]
An optional feature which allows valid users to take away the active logins and continue login by destroying other old sessions.

**Comment by adaptifyDesigns** [comment]
Hi Joel, are you still actively developing this plugin? The feature you outline here is one that I would like to see. Do you still plan to implement it? 

Cheers!

**Comment by Joel-James** [comment]
@adaptifyDesigns Yes. Development is active :yum: I hope this feature can be implemented soon after I complete my current project.

**Comment by adaptifyDesigns** [comment]
@Joel-James Ok, thanks Joel. Looking forward to it.

**Comment by flamefilm** [comment]
Hi,

I made this modification in the class-f-loggedin.php:
`    private function reached_limit( $user_id ) {
        
  //      if ( $this->bypass( $user_id ) ) {
  //          return false;
  //      }
        
        // Get maximum active logins allowed.
        $maximum = intval( get_option( 'loggedin_maximum', 1 ) );
        
        $manager = WP_Session_Tokens::get_instance( $user_id );
	
        $count = count( $manager->get_all() );
        
 //       return $count >= $maximum;
        // Check if the maximum active logins allowed is equal or less then current
        if ($count >= $maximum) {
          $all_sessions = $manager->get_all();
          $first_login = $all_sessions[0]['login'];
          $nowtime = time();
          // Check the time passed since first login
          if( $nowtime-$first_login > 90 ) {
            $manager->destroy_all();
            return false;
          } else {
              return true;
          }
        }
        return false;
    }`

What do you think? I am not a php programmer, just found out this. But it seems it is working.
So you can set the time here in seconds:
` if( $nowtime-$first_login > 90 ) {`
If this time is more than the time passed since the first login of the user then it won't let they in. If this is less, then it destroys the old user sessions and let the user in.

I try to figure it out, how to destroy only the oldest session and not all the sessions of the user.
Tried this, but it is not working:
`$manager->destroy( $all_sessions[0] );`

Any idea?

**Comment by Joel-James** [comment]
This is available in latest version.
